openapi: 3.0.1
info:
  title: Forager-Compass API
  description: >-
    This server, and the related REST API's, are used to faciliate playing the Pax Pamir boardgame remotely.  Client applications wishing to use this API, would only need to worry about the view or presentation aspect of actual gameplay.


    All state information is retained by the server, including games in progress, player base, rule enforcement, game replay and undo operations.



    You can find out more about the actual board game directly from the manafuacturer at  [Wehrlegig Games](http://wehrlegig.com)

  contact:
    email: seung2@pdx.edu, camilo3@pdx.edu, mwignall@pdx.edu
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: 1.0.0

servers:
  - url: "https://foragecompass.herokuapp.com/"
  - url: "http://localhost:3001"
tags:
  - name: category
    description: Information pertaining to the the types of items tracked by Forager-Compass
  - name: location
    description: Information stored for discovered locations of Forage-Compass items
paths:
  /categories:
    get:
      tags:
        - category
      summary: Get all Forager-Compass supported varieties
      description: Returns all varietiel information, as a JSON object containing Categories and Varities within each
      operationId: getCategories
      responses:
        200:
          description: Successfull operation
          content: {}
  /locations:
    get:
      tags:
        - location
      summary: Get all known Forager-Compass locations reported by users
      description: >-
        Returns all location information, as a JSON object containing location name, latitude, longitude and type of item (variety) discovered

        For valid responses, varietal should match one of the varieties supported
        See: `/categories` for more information
      operationId: getLocations
      parameters:
        - name: variety
          in: query
          description: Variety of locations to filter to, leave blank for all known
          required: false
          schema:
            type: string
            format: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/locations"
        "406":
          description: Invalid variety specified
          content: {}

components:
  schemas:
    locations:
      required:
        - latitude
        - longitude
        - variety
        - name
      type: object
      properties:
        _id:
          type: string
          format: ObjectId
          uniqueItems: true
          example: 605a6421d763780935d80eb1
          readonly: true
        name:
          type: string
          example: Bob's secret berry bush
        latitude:
          type: number
          format: float
          example: 145.535838
        longitude:
          type: number
          format: float
          example: -122.727242
        variety:
          type: string
          format: string
          example: Marionberry

  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
